In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
from sklearn import set_config
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, OneHotEncoder
from sklearn.base import BaseEstimator, TransformerMixin, OneToOneFeatureMixin
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import set_config

set_config(transform_output="pandas")

In [3]:
df = pd.read_csv("./dataset/swarm_training.csv")
unknown_behaviour = pd.read_csv("./dataset/unknown_swarm_behaviour.csv")
df.head()

,yC187,yC148,yC7,yC111,yC32,xC54,xC148,yC193,xC61,yC81,...,yS191,yS14,xS2,yS6,yC65,xC18,nS64,yC166,nS55,yS122
0,0.0,50.0,24.50,50.0,100.0,0.0,-1.2,17.50,1.0,94.0,...,0.0,-0.84,0.0,0.0,12.500,0.25,0.0,12.500,0.0,0.0
1,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.000,0.0,0.0
2,19.0,-10.5,-7.75,-14.0,-27.0,-17.0,4.8,-5.75,11.0,-26.0,...,0.0,0.00,0.0,0.0,-2.875,2.50,1.0,-1.375,0.0,0.0
3,-2.0,16.0,-2.00,-2.5,-10.0,-32.0,0.4,-8.00,15.0,5.0,...,0.0,0.00,0.0,0.0,2.625,-8.00,0.0,4.000,0.0,0.0
4,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.98,0.0,0.0,0.000,0.00,0.0,0.000,0.0,0.0

In [9]:
columns = df.columns
print("Swarm_Behaviour" in columns)

False